<a href="https://colab.research.google.com/github/SameerR007/sentiment_analysis/blob/main/sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
dataset = pd.read_csv('a1_RestaurantReviews_HistoricDump.tsv', delimiter = '\t', quoting = 3)

In [32]:
dataset.shape

(900, 2)

In [33]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [34]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [35]:
docs=dataset["Review"]

In [36]:
tokenizer.fit_on_texts(docs)

In [37]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'i': 3,
 'was': 4,
 'a': 5,
 'to': 6,
 'is': 7,
 'this': 8,
 'of': 9,
 'food': 10,
 'it': 11,
 'not': 12,
 'in': 13,
 'for': 14,
 'place': 15,
 'good': 16,
 'service': 17,
 'we': 18,
 'great': 19,
 'very': 20,
 'my': 21,
 'had': 22,
 'so': 23,
 'with': 24,
 'that': 25,
 'were': 26,
 'be': 27,
 'have': 28,
 'are': 29,
 'on': 30,
 'back': 31,
 'they': 32,
 'you': 33,
 'but': 34,
 'here': 35,
 'at': 36,
 'like': 37,
 'go': 38,
 'our': 39,
 'time': 40,
 'all': 41,
 'will': 42,
 'as': 43,
 'there': 44,
 'an': 45,
 'really': 46,
 'just': 47,
 'best': 48,
 'ever': 49,
 'their': 50,
 'never': 51,
 'friendly': 52,
 'nice': 53,
 'one': 54,
 'up': 55,
 'also': 56,
 'would': 57,
 'amazing': 58,
 'restaurant': 59,
 'again': 60,
 'if': 61,
 'delicious': 62,
 'only': 63,
 'out': 64,
 'been': 65,
 'vegas': 66,
 'your': 67,
 'by': 68,
 'no': 69,
 'did': 70,
 'staff': 71,
 'me': 72,
 "don't": 73,
 "i've": 74,
 "i'm": 75,
 'from': 76,
 'what': 77,
 'he': 78,
 'which': 79,
 'when': 

In [38]:
len(tokenizer.word_index)

1931

In [39]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[385, 151, 8, 15],
 [529, 7, 12, 16],
 [12, 140, 2, 1, 530, 4, 47, 531],
 [532, 68, 273, 1, 533, 321, 823, 824, 204, 825, 826, 386, 2, 151, 11],
 [1, 152, 30, 1, 105, 4, 19, 2, 23, 26, 1, 153],
 [141, 3, 274, 205, 827, 2, 3, 142, 21, 322, 241],
 [828, 11, 128, 120, 25, 129],
 [1,
  387,
  26,
  37,
  829,
  2,
  33,
  106,
  275,
  32,
  22,
  65,
  92,
  55,
  830,
  9,
  40,
  121,
  323,
  534,
  5,
  831],
 [1, 206, 26, 19, 130],
 [5, 19, 535],
 [17, 4, 20, 832],
 [57, 12, 38, 31],
 [1,
  536,
  22,
  69,
  388,
  77,
  23,
  49,
  30,
  77,
  3,
  22,
  6,
  107,
  11,
  154,
  537,
  55,
  121,
  833,
  276],
 [3, 207, 1, 834, 835, 836, 84, 24, 837, 838],
 [3, 4, 839, 122, 3, 4, 96, 208, 25, 4, 840, 538],
 [3, 4, 841, 122, 69, 842, 843, 844, 63],
 [324, 389],
 [178, 4, 5, 163, 155, 13, 17],
 [8, 15, 7, 12, 164, 67, 40, 539, 845, 66],
 [70, 12, 37, 36, 41],
 [1, 846, 847],
 [1, 10, 58],
 [17, 7, 56, 540],
 [3, 106, 388, 848, 1, 849, 7, 47, 390],
 [23, 32, 850],
 [851, 165, 1, 541

In [40]:
docs

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
895    I want to first say our server was great and w...
896                       The pizza selections are good.
897                I had strawberry tea, which was good.
898    Highly unprofessional and rude to a loyal patron!
899                         Overall, a great experience.
Name: Review, Length: 900, dtype: object

In [48]:
import numpy as np
import statistics
statistics.median((docs.apply(len)).values)

51.0

In [50]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post',maxlen=51)
sequences

array([[ 385,  151,    8, ...,    0,    0,    0],
       [ 529,    7,   12, ...,    0,    0,    0],
       [  12,  140,    2, ...,    0,    0,    0],
       ...,
       [   3,   22, 1928, ...,    0,    0,    0],
       [ 324, 1929,    2, ...,    0,    0,    0],
       [ 210,    5,   19, ...,    0,    0,    0]], dtype=int32)

In [51]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [53]:
model = Sequential()
model.add(Embedding(1932,2,input_length=51))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

In [54]:
X=sequences

In [55]:
Y=dataset['Liked']

In [56]:
X

array([[ 385,  151,    8, ...,    0,    0,    0],
       [ 529,    7,   12, ...,    0,    0,    0],
       [  12,  140,    2, ...,    0,    0,    0],
       ...,
       [   3,   22, 1928, ...,    0,    0,    0],
       [ 324, 1929,    2, ...,    0,    0,    0],
       [ 210,    5,   19, ...,    0,    0,    0]], dtype=int32)

In [57]:
Y=Y.to_numpy()

In [58]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X,Y,epochs=5)

Epoch 1/5
29/29 [==============================] - 1s 10ms/step - loss: 0.6901 - acc: 0.5356
Epoch 2/5
29/29 [==============================] - 0s 9ms/step - loss: 0.6791 - acc: 0.5667
Epoch 3/5
29/29 [==============================] - 0s 9ms/step - loss: 0.6620 - acc: 0.5833
Epoch 4/5
29/29 [==============================] - 0s 9ms/step - loss: 0.6057 - acc: 0.7078
Epoch 5/5
29/29 [==============================] - 0s 10ms/step - loss: 0.5201 - acc: 0.7656


In [59]:
abc=[input()]

good


In [60]:
seq=tokenizer.texts_to_sequences(abc)

In [61]:
seq

[[16]]

In [63]:
inp=pad_sequences(seq,padding='post',maxlen=51)

In [64]:
inp

array([[16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0]], dtype=int32)

In [65]:
model.predict(inp)

1/1 [==============================] - 0s 122ms/step


array([[0.71028906]], dtype=float32)